name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # runs every 6 hours

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # ✅ Supported flags
          SHOW_TIMEZONE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LINES_OF_CODE: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          COMMIT_MESSAGE: "📊 Update WakaTime stats"
          COMMIT_USERNAME: GitHubActionBot
          COMMIT_EMAIL: action-bot@github.com
