name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # You can change to "0 0 * * *" for daily

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: "🟩🟨🟧🟥⬜"
          CODE_LANG: rust
          TIME_RANGE: last_year
          LANG_COUNT: 10
          SHOW_TIMEZONE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          SHOW_LINES_OF_CODE: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE_PER_REPO: true
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML
          COMMIT_MESSAGE: "📊 Update WakaTime stats"
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: M-F-Tushar
          AUTHOR_EMAIL: www.mahirfaysaltushar@gmail.com

